### ISSUE TITLE
Is it Multi Document ACID compliant?

### ISSUE THREAD

**Issue by ghost** [igd-geo/mongomvcc#3]

**Comment by michel-kraemer** [comment]
Can you please describe what you're trying to achieve? Maybe give a code example or something like this? Thanks!

Michel

**Comment by ghost** [comment]
We were trying to create an in memory MVCC layer using redis so that we could modify mutiple documents in multiple collections in mongodb without data corruption or data loss and having ACID guarantee like SQL. So I thought this might already have it and we would not need to implement it.

**Comment by michel-kraemer** [comment]
Yes, this use case is possible with MongoMVCC. You can modify multiple documents and then /commit/ the transaction to make the changes visible to other clients at once (i.e. atomically).

Let me know if this answers your question. If so please close the issue. Thanks.

**Comment by ghost** [comment]
Thanks. Now were going to dig into your code and see how you implemented it.
