### ISSUE TITLE
question

### ISSUE THREAD

**Issue by publicocean0** [igd-geo/mongomvcc#4]
Hi  i m developping a little database and i d like to understand how to handle transactions. In particular way distributed transactions .Unfortunatelly at university they didnt teach how to write a MVCC transation manager . Is there some little book or online page for learning?
I m implemeting replication of data in different nodes i dont know how to handle
the case : 
document X is saved in Node A ... when it arrives to node B , in the while optimistick lock is changed. 
the simpliest solution is to use distributed lock, but i think performance will be not very good.

**Comment by michel-kraemer** [comment]
@publicocean0 I'm not sure if I can help you with database-specific questions. If you want to know more about MVCC you might be best off with a quick google search. There's a lot about this topic on the net.

Regarding MongoMVCC, I implemented a model that is very similar to the one Git uses:
http://gitready.com/beginner/2009/02/17/how-git-stores-your-data.html

I hope this helps.

Cheers,
Michel
